name: Bug Report
description: Relate um bug para nos ajudar a melhorar.
title: "[BUG] - "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por abrir um relatório de bug! Por favor, preencha o formulário abaixo para que possamos investigar.

  - type: input
    id: environment
    attributes:
      label: Ambiente
      description: Em qual ambiente o erro ocorreu? (ex: local, produção, container Docker, etc.)
      placeholder: ex: Docker no Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Descreva claramente o que está acontecendo.
      placeholder: O que você esperava que acontecesse vs o que realmente aconteceu.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Passos para reproduzir o erro.
      placeholder: |
        1. Vá até '...'
        2. Clique em '...'
        3. Veja o erro...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs e mensagens de erro
      description: Cole aqui qualquer mensagem de erro relevante.
      render: shell

  - type: input
    id: version
    attributes:
      label: Versão do sistema
      description: Versão do software onde o erro foi identificado.
      placeholder: ex: v1.2.0

  - type: dropdown
    id: severity
    attributes:
      label: Severidade
      description: Quão grave é o problema?
      options:
        - Baixa
        - Média
        - Alta
        - Crítica
