name: Bug Report
description: Relate um bug para nos ajudar a melhorar o projeto.
title: "[BUG] - "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por abrir um relatório de bug! Por favor, preencha o formulário abaixo para nos ajudar a entender e resolver o problema.

  - type: input
    id: environment
    attributes:
      label: Ambiente
      description: "Em qual ambiente o erro ocorreu? (ex: local, produção, Docker, etc.)"
      placeholder: "ex: Docker no Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: "Explique o que deveria acontecer e o que está realmente acontecendo."
      placeholder: "Comportamento esperado vs observado"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: "Liste as etapas necessárias para reproduzir o problema."
      placeholder: |
        1. Vá até '...'
        2. Clique em '...'
        3. Veja o erro...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs e mensagens de erro
      description: "Inclua aqui qualquer mensagem de erro relevante."
      render: shell

  - type: input
    id: version
    attributes:
      label: Versão
      description: "Versão do sistema ou software em que o bug foi encontrado."
      placeholder: "ex: v1.2.0"

  - type: dropdown
    id: severity
    attributes:
      label: Severidade
      description: "Qual o impacto do problema?"
      options:
        - Baixa
        - Média
        - Alta
        - Crítica
