nname: Bug Report
description: Relate um bug para nos ajudar a melhorar o projeto.
title: "[BUG] - "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por abrir um relatório de bug! Por favor, preencha o formulário abaixo para nos ajudar a entender e resolver o problema.

  - type: input
    id: environment
    attributes:
      label: Ambiente
      description: "Em qual ambiente o erro ocorreu? (ex: local, produção, Docker, etc.)"
      placeholder: "ex: Docker no Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: "Explique o que deveria acontecer e o que está realmente acontecendo."
      placeholder: "Comportamento esperado vs observado"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: "Liste as
